blog/blueprints/admin.py
"""
    管理员

    url_for接受一个函数名作为参数，也接受对应url规则的命名变量
    未知的变量会添加到url尾部作为查询字符串

    flask中request对象的实现原理：
        1。 Thread Local
            每一个请求是一个独立的线程，请求之间的信息需要完全隔离开。避免冲突，实现线程安全
            Thread Local是一种特殊状态的对象，状态对于线程是隔离的，线程对Thread Local的修改
            并不会影响到其他的线程
        2. 主要的实现依赖于三个类：
            Local， LocalStack， LocalProxy

            __solts__类变量的作用是限制添加到实例对象上的属性
            __storage = {线程ID：{name: value}}
            线程ID通过掉用get_ident函数来实现

            比如：
                获取local.age属性的时候 --> 触发__getattr__函数
                内部调用get_ident函数获取当前线程的ID，然后去__storage
                字典中进行查找是否存在对应的属性
                设置属性的时候也是同理
            __release_local__ 就是将当前的线程从__storage字典中删除

"""

import os

from flask import Blueprint, send_from_directory
from flask import render_template
from flask import request
from flask import current_app
from flask import flash
from flask import redirect
from flask import url_for
from flask_dropzone import random_filename

from flask_login import login_required, current_user
from blog.models import Post, Category, Comment, Link, Admin
from blog.forms import PostForm, CategoryForm, LinkForm, SettingForm, UploadForm
from blog.extensions import db
from blog.utils import redirect_back, commit_data
from blog.utils import confirm_required
from blog.utils import resize_avatar
from flask_ckeditor import upload_fail, upload_success
admin_bp = Blueprint('admin_bp', __name__)  # 创建蓝图对象


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
@confirm_required
def settings():
    """
        博客的设置页面

        login_required装饰器实现了视图保护，只有登录之后的用户才能访问被视图保护装饰的视图函数

        ** 当为视图函数添加多个装饰器的时候，route装饰器应该位于最外层

        当未登录的用户访问需要登录才能请求的视图函数的时候，如果添加了login_required装饰器
        程序会自动重定向到登录页面，此时需要通过login_manager的login_view属性设置重定向的视图函数
        并且通过login_message_category设置提示消息的类别，login_message设置提示消息的内容
        具体见extensions文件

        在重定向的url中，会自动包含上一个页面的next参数，当登录了之后，会自动重定向到next参数指定的页面

        如果想为整个蓝图添加视图保护，可以使用请求钩子，添加login_required装饰器

        常见的响应状态码：
            200   成功
            201   请求成功，并且新建了资源
            204   请求成功，但是没有内容返回
            301   永久重定向
            302   临时重定向
            304   请求的内容没有修改，Not Modified 重定向到缓存
            404   请求的资源不存在
            400   请求参数不正确
            401   请求的用户没有认证
            403   请求的用户没有权限
            500   服务器内部错误
    :return:
    """
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        commit_data('add', current_user)
        flash('修改设置成功', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
@login_required
@confirm_required
def manage_post():
    """
        文章管理页面
    :return:
    """

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_MANAGE_POST_PER_PAGE']

    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)

    posts = pagination.items

    return render_template('admin/manage_post.html', posts=posts, pagination=pagination, page=page)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_post():
    """
        添加文章页面
    :return:
    """
    form = PostForm()
    if form.validate_on_submit():
        """表单验证通过"""
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        # category_id = form.category.data  效果同上
        post = Post(title=title, body=body, category=category)
        db.session.add(post)
        db.session.commit()
        flash('保存成功', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))

    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/new/category', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_category():
    """
        新建文章分类
    :return:
    """

    form = CategoryForm()
    if form.validate_on_submit():
        """进行表单验证的时候，会自动查找当前的类中是否存在validate_字段名开头的属性
           如果存在的话，会在验证的时候，将这部分的数据也进行验证
        """
        name = form.name.data
        if Category.query.filter(Category.name == name).first():
            flash('当前分类已经存在，请勿重复添加', 'warning')
            return redirect_back()
        category = Category()
        category.name = name

        commit_data('add', category)
        flash('添加新分类成功！', 'success')
        return redirect(url_for('admin_bp.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/new/link', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_link():
    """
        新建链接
    :return:
    """
    form = LinkForm()
    link = Link()
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        commit_data('add', link)
        flash('新建链接成功', 'success')
        return redirect(url_for('admin_bp.manage_link'))

    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/category/manage')
@login_required
@confirm_required
def manage_category():
    """
        管理分类
    :return:
    """
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_category(category_id):
    """
        编辑分类
    :param category_id:
    :return:
    """

    form = CategoryForm()
    category = Category.query.get(category_id)
    if form.validate_on_submit():
        category.name = form.name.data
        commit_data('add', category)
        flash('编辑成功', 'success')
        return redirect(url_for('admin_bp.manage_category'))

    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_category(category_id):
    """
        删除分类
    :param category_id:
    :return:
    """

    category = Category.query.get_or_404(category_id)

    if category.name == 'Default':
        flash('不允许删除默认的分类', 'warning')
        return redirect(url_for('admin_bp.manage_category'))

    category.delete()

    flash('删除该分类成功', 'success')

    return redirect(url_for('admin_bp.manage_category'))


@admin_bp.route('/comment/manage')
@login_required
@confirm_required
def manage_comment():
    """
        管理评论
    :return:
    """
    filter_ = request.args.get('filter', 'all')  # 获取评论页面的筛选规则
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    if filter_ == 'admin':
        # 来自管理员的评论
        pagination = Comment.query.filter_by(from_admin=True).order_by(
            Comment.timestamp.desc()).paginate(page, per_page=per_page)

    elif filter_ == 'unread':
        # 未读评论
        pagination = Comment.query.filter_by(reviewed=False).order_by(
            Comment.timestamp.desc()).paginate(page, per_page=per_page)

    else:
        pagination = Comment.query.order_by(
            Comment.timestamp.desc()).paginate(page, per_page=per_page)  # 获取所有未审核评论

    comments = pagination.items

    return render_template(
        'admin/manage_comment.html', comments=comments,
        pagination=pagination)


@admin_bp.route('/link/manage')
@login_required
@confirm_required
def manage_link():
    """
        管理链接，这里的链接之所以能不传入模板
        是因为在模板上下文处理函数中默认传入模板中的
    :return:
    """
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_link(link_id):
    """
        编辑文章的链接
    :param link_id:
    :return:
    """
    form = LinkForm()
    link = Link.query.get_or_404(link_id, description='当前指定的链接不存在')
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        commit_data('add', link)
        flash('编辑成功', 'success')
        return redirect(url_for('admin_bp.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_link(link_id):
    """
        删除链接
    :param link_id:
    :return:
    """
    link = Link.query.get_or_404(link_id)
    commit_data('delete', link)
    flash('删除链接成功', 'success')
    return redirect(url_for('admin_bp.manage_link'))


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_post(post_id):
    """
        编辑文章
    :return:
    """
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    # form.category.choices = [(i.id, i.name) for i in Category.query.order_by(
    #     Category.name).all()]  # 指定分类下拉选项的内容
    if form.validate_on_submit():
        """表单验证通过的逻辑"""
        post.title = form.title.data
        post.body = form.body.data
        post.category_id = form.category.data
        commit_data('add', post)
        flash('编辑文章成功！！', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))

    form.title.data = post.title  # 将文章的内容进行展示
    form.body.data = post.body
    form.category.data = post.category_id

    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_post(post_id):
    """
        删除文章
    :param post_id:
    :return:
    """

    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()

blog/blueprints/auth.py
"""
    蓝图对象是一个用于注册路由等操作的临时对象
    蓝图中的视图函数通过蓝图实例提供的route()装饰器注册
    使用蓝图实例的errorhandler()装饰器可以把错误处理器注册到蓝图上
    这些错误处理器只会处理访问该蓝图中的视图函数时发生的错误，使用蓝图实例的app_errorhandler()装饰器
    可以注册一个全局的错误处理器
        404和405错误仅会被全局的错误处理函数捕捉，如果区分蓝图url下的404和405错误
        可以在全局定义的404错误处理函数中使用request.path.statrswith(蓝图的url前缀)
        来判断请求的url是否属于某一个蓝图

    蓝图中，可以使用请求钩子注册的请求处理函数是蓝图独有的，只有蓝图中的视图函数会触发相应的请求处理函数
    另外，可以在蓝图中使用before_app_request, after_app_request,teardown_app_request, before_app_first_request方法
    这些方法注册的请求处理函数是全局的

    模板上下文处理函数
        使用context_processor装饰器注册蓝图特有的模板上下文处理器，使用app_context_processor装饰器则会注册程序全局的模板上下文处理器
        蓝图对象也可以使用app_template_global(), app_template_filter(), app_template_test()装饰器
        注册全局模板全局函数，模板过滤器函数和模板测试器

    并不是所有程序实例提供的方法和属性都可以在蓝图对象中使用，蓝图对象中只提供了少量用于注册处理函数的方法
    大部分的属性和方法仍然需要通过程序实例app获取，比如配置config属性和自定义注册命令的cli.command()装饰器

    为了使蓝图能够发挥作用，我们必须把蓝图注册到程序实例app上
"""

from flask import Blueprint, current_app
from flask import redirect, url_for
from flask import flash
from flask import render_template
from flask import send_from_directory

from flask_login import current_user, login_user, logout_user, login_required
from blog.celery_tasks.email.tasks import send_confirm_email, resend_confirm_email
from blog.forms import LoginForm, RegisterForm
from blog.models import Admin
from blog.utils import redirect_back, commit_data, generate_confirmation_token, confirm_token
from blog.settings import Operations


auth_dp = Blueprint('auth', __name__)


@auth_dp.route('/login', methods=['GET', 'POST'])
def login():
    """用户登陆"""
    if current_user.is_authenticated:
        """如果用户经过认证,重定向到首页"""
        return redirect(url_for('blog.index'))

    form = LoginForm()  # 渲染登录的表单

    if form.validate_on_submit():
        """表单验证成功的逻辑"""
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        admin = Admin.query.filter_by(username=username).first()
        if admin:
            """验证用户名和密码"""
            if username == admin.username and admin.validate_password(password):
                login_user(admin, remember)  # 实现登陆用户的会话管理，记录用户的登陆状态
                flash('欢迎回来！！！')
                return redirect_back()  # 返回上一个页面
            else:
                flash('无效的用户名或者是密码')
        else:
            flash('不是管理员帐号')

    return render_template('auth/login.html', form=form)


@auth_dp.route('logout')
def logout():
    """
        用户登出 使用flask_login的logout()函数实现

        login_out()函数会登出用户并且清除session中存储的用户id和remember_token的值
    """

    logout_user()
    flash('退出成功')
    return redirect_back()


@auth_dp.route('/register', methods=['GET', 'POST'])
def register():
    """用户注册"""
    form = RegisterForm()

    if form.validate_on_submit():
        name = form.name.data
        username = form.username.data
        password = form.password.data
        blog_title = form.blog_title.data
        blog_sub_title = form.blog_sub_title.data
        about = form.about.data
        email = form.email.data
        # 添加一个用户
        admin = Admin(
            name=name, username=username, blog_title=blog_title,
            blog_sub_title=blog_sub_title, about=about, email=email
        )
        admin.set_password(password)
        commit_data('add', admin)
        token = generate_confirmation_token(user=admin, op=Operations.CONFIRM)  # 生成一个签名
        send_confirm_email(user=admin, token=token)  # 发送确认邮件
        flash('电子邮件已经发送，请注意查收！', 'success')
        return redirect(url_for('.login'))
    return render_template('auth/register.html', form=form)


@auth_dp.route('/confirm/<path:token>')
@login_required
def confirm(token):
    """
        确认邮箱
    :param token: 签名
    :return:
    """
    if confirm_token(user=current_user, token=token, op=Operations.CONFIRM):
        """签名验证成功的逻辑"""
        flash('邮箱验证成功', 'success')
        return redirect(url_for('blog.index'))
    else:
        flash('邮箱验证失败！签名无效或者已经过期', 'warning')
        return redirect(url_for('.reconfirm_email'))


@auth_dp.route('/resend/email')
@login_required
def reconfirm_email():
    # 重新生成签名
    token = generate_confirmation_token(current_user, op=Operations.CONFIRM)
    # 重新发送短信验证码
    user = current_user
    resend_confirm_email(user, token=token)
    flash('邮件发送成功，请注意查收！', 'success')
    return redirect(url_for('.login'))


@auth_dp.route('/avatars/<path:filename>')
def get_avatar(filename):
    """
        获取用户头像,将目录中的文件返回
    :return:
    """
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)

blog/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}{% endblock title %} - {{ admin.blog_title|default('Blog Title') }}</title>
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'perfect_blue')) }}"
              type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">

    {% endblock head %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('blog.index') }}">{{ admin.blog_title }}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    {# 渲染bootstarp主题的导航栏，使用bootstarp自带的render_nav_item宏实现 #}
                    {{ render_nav_item('blog.index', '主页') }}
                    {{ render_nav_item('blog.about', '关于') }}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                新 <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin_bp.new_post') }}">文章</a>
                                <a class="dropdown-item" href="{{ url_for('admin_bp.new_category') }}">分类</a>
                                <a class="dropdown-item" href="{{ url_for('admin_bp.new_link') }}">链接</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                管理 <span class="caret"></span>
                                {% if unread_comments %}
                                    <span class="badge badge-success">新</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin_bp.manage_post') }}">文章</a>
                                <a class="dropdown-item" href="{{ url_for('admin_bp.manage_category') }}">分类</a>
                                <a class="dropdown-item" href="{{ url_for('admin_bp.manage_comment') }}">
                                    评论
                                    {% if unread_comments %}
                                        <span class="badge badge-success">{{ unread_comments }}</span>
                                    {% endif %}
                                </a>
                                <a class="dropdown-item" href="{{ url_for('admin_bp.manage_link') }}">链接</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                             <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">
                                上传头像 <span class="caret"></span>
                            </a>
                             <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin_bp.upload_avatar') }}">上传头像</a>
                             </div>
                        </li>
                        {{ render_nav_item('admin_bp.settings', '设置') }}
                    {% endif %}
                </ul>
            </div>
            <div class="dropdown nav-item">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-expanded="false">
                    <img class="avatar-xs"
                         src="{{ url_for('auth.get_avatar', filename=current_user.avatar_l) }}">
                    <span class="caret"></span>
                </a>
            </div>
        </div>
    </nav>
{% endblock nav %}

{# 渲染flash消息 #}
<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}
    {% block content %}{% endblock content %}
    {% block footer %}
        <footer>
            <p class="float-left">
                <small> &copy; 2018 <a href="http://greyli.com" title="Written by Grey Li">王栋</a> -
                    <a href="https://github.com/greyli/bluelog" title="Fork me on GitHub">GitHub</a> -
                    <a href="http://helloflask.com" title="A HelloFlask project">博客</a>
                </small>
            </p>
            <p class="float-right">
                <small>
                    {# 根据用户的登录状态渲染不同的内容 #}
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout', next=request.full_path) }}">退出</a>
                    {% else %}
                        <a href="{{ url_for('auth.login', next=request.full_path) }}">登录</a>
                        <a href="{{ url_for('auth.register', next=request.full_path) }}">注册</a>
                    {% endif %}
                </small>
            </p>
        </footer>
    {% endblock footer %}
</main>

{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.lang("zh-CN") }}
{% endblock %}
</body>
</html>