blog/blueprints/admin.py
"""
    管理员

    url_for接受一个函数名作为参数，也接受对应url规则的命名变量
    未知的变量会添加到url尾部作为查询字符串

    flask中request对象的实现原理：
        1。 Thread Local
            每一个请求是一个独立的线程，请求之间的信息需要完全隔离开。避免冲突，实现线程安全
            Thread Local是一种特殊状态的对象，状态对于线程是隔离的，线程对Thread Local的修改
            并不会影响到其他的线程
        2. 主要的实现依赖于三个类：
            Local， LocalStack， LocalProxy

            __solts__类变量的作用是限制添加到实例对象上的属性
            __storage = {线程ID：{name: value}}
            线程ID通过掉用get_ident函数来实现

            比如：
                获取local.age属性的时候 --> 触发__getattr__函数
                内部调用get_ident函数获取当前线程的ID，然后去__storage
                字典中进行查找是否存在对应的属性
                设置属性的时候也是同理
            __release_local__ 就是将当前的线程从__storage字典中删除

"""

import os

from flask import Blueprint, send_from_directory
from flask import render_template
from flask import request
from flask import current_app
from flask import flash
from flask import redirect
from flask import url_for
from flask_dropzone import random_filename

from flask_login import login_required, current_user
from blog.models import Post, Category, Comment, Link, Admin
from blog.forms import PostForm, CategoryForm, LinkForm, SettingForm, UploadForm
from blog.extensions import db
from blog.utils import redirect_back, commit_data
from blog.utils import confirm_required
from blog.utils import resize_avatar
from flask_ckeditor import upload_fail, upload_success
admin_bp = Blueprint('admin_bp', __name__)  # 创建蓝图对象


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
@confirm_required
def settings():
    """
        博客的设置页面

        login_required装饰器实现了视图保护，只有登录之后的用户才能访问被视图保护装饰的视图函数

        ** 当为视图函数添加多个装饰器的时候，route装饰器应该位于最外层

        当未登录的用户访问需要登录才能请求的视图函数的时候，如果添加了login_required装饰器
        程序会自动重定向到登录页面，此时需要通过login_manager的login_view属性设置重定向的视图函数
        并且通过login_message_category设置提示消息的类别，login_message设置提示消息的内容
        具体见extensions文件

        在重定向的url中，会自动包含上一个页面的next参数，当登录了之后，会自动重定向到next参数指定的页面

        如果想为整个蓝图添加视图保护，可以使用请求钩子，添加login_required装饰器

        常见的响应状态码：
            200   成功
            201   请求成功，并且新建了资源
            204   请求成功，但是没有内容返回
            301   永久重定向
            302   临时重定向
            304   请求的内容没有修改，Not Modified 重定向到缓存
            404   请求的资源不存在
            400   请求参数不正确
            401   请求的用户没有认证
            403   请求的用户没有权限
            500   服务器内部错误
    :return:
    """
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        commit_data('add', current_user)
        flash('修改设置成功', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about
    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
@login_required
@confirm_required
def manage_post():
    """
        文章管理页面
    :return:
    """

    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_MANAGE_POST_PER_PAGE']

    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)

    posts = pagination.items

    return render_template('admin/manage_post.html', posts=posts, pagination=pagination, page=page)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_post():
    """
        添加文章页面
    :return:
    """
    form = PostForm()
    if form.validate_on_submit():
        """表单验证通过"""
        title = form.title.data
        body = form.body.data
        category = Category.query.get(form.category.data)
        # category_id = form.category.data  效果同上
        post = Post(title=title, body=body, category=category)
        db.session.add(post)
        db.session.commit()
        flash('保存成功', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))

    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/new/category', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_category():
    """
        新建文章分类
    :return:
    """

    form = CategoryForm()
    if form.validate_on_submit():
        """进行表单验证的时候，会自动查找当前的类中是否存在validate_字段名开头的属性
           如果存在的话，会在验证的时候，将这部分的数据也进行验证
        """
        name = form.name.data
        if Category.query.filter(Category.name == name).first():
            flash('当前分类已经存在，请勿重复添加', 'warning')
            return redirect_back()
        category = Category()
        category.name = name

        commit_data('add', category)
        flash('添加新分类成功！', 'success')
        return redirect(url_for('admin_bp.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/new/link', methods=['GET', 'POST'])
@login_required
@confirm_required
def new_link():
    """
        新建链接
    :return:
    """
    form = LinkForm()
    link = Link()
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        commit_data('add', link)
        flash('新建链接成功', 'success')
        return redirect(url_for('admin_bp.manage_link'))

    return render_template('admin/new_link.html', form=form)


@admin_bp.route('/category/manage')
@login_required
@confirm_required
def manage_category():
    """
        管理分类
    :return:
    """
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_category(category_id):
    """
        编辑分类
    :param category_id:
    :return:
    """

    form = CategoryForm()
    category = Category.query.get(category_id)
    if form.validate_on_submit():
        category.name = form.name.data
        commit_data('add', category)
        flash('编辑成功', 'success')
        return redirect(url_for('admin_bp.manage_category'))

    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_category(category_id):
    """
        删除分类
    :param category_id:
    :return:
    """

    category = Category.query.get_or_404(category_id)

    if category.name == 'Default':
        flash('不允许删除默认的分类', 'warning')
        return redirect(url_for('admin_bp.manage_category'))

    category.delete()

    flash('删除该分类成功', 'success')

    return redirect(url_for('admin_bp.manage_category'))


@admin_bp.route('/comment/manage')
@login_required
@confirm_required
def manage_comment():
    """
        管理评论
    :return:
    """
    filter_ = request.args.get('filter', 'all')  # 获取评论页面的筛选规则
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    if filter_ == 'admin':
        # 来自管理员的评论
        pagination = Comment.query.filter_by(from_admin=True).order_by(
            Comment.timestamp.desc()).paginate(page, per_page=per_page)

    elif filter_ == 'unread':
        # 未读评论
        pagination = Comment.query.filter_by(reviewed=False).order_by(
            Comment.timestamp.desc()).paginate(page, per_page=per_page)

    else:
        pagination = Comment.query.order_by(
            Comment.timestamp.desc()).paginate(page, per_page=per_page)  # 获取所有未审核评论

    comments = pagination.items

    return render_template(
        'admin/manage_comment.html', comments=comments,
        pagination=pagination)


@admin_bp.route('/link/manage')
@login_required
@confirm_required
def manage_link():
    """
        管理链接，这里的链接之所以能不传入模板
        是因为在模板上下文处理函数中默认传入模板中的
    :return:
    """
    return render_template('admin/manage_link.html')


@admin_bp.route('/link/<int:link_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_link(link_id):
    """
        编辑文章的链接
    :param link_id:
    :return:
    """
    form = LinkForm()
    link = Link.query.get_or_404(link_id, description='当前指定的链接不存在')
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        commit_data('add', link)
        flash('编辑成功', 'success')
        return redirect(url_for('admin_bp.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('/link/<int:link_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_link(link_id):
    """
        删除链接
    :param link_id:
    :return:
    """
    link = Link.query.get_or_404(link_id)
    commit_data('delete', link)
    flash('删除链接成功', 'success')
    return redirect(url_for('admin_bp.manage_link'))


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
@confirm_required
def edit_post(post_id):
    """
        编辑文章
    :return:
    """
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    # form.category.choices = [(i.id, i.name) for i in Category.query.order_by(
    #     Category.name).all()]  # 指定分类下拉选项的内容
    if form.validate_on_submit():
        """表单验证通过的逻辑"""
        post.title = form.title.data
        post.body = form.body.data
        post.category_id = form.category.data
        commit_data('add', post)
        flash('编辑文章成功！！', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))

    form.title.data = post.title  # 将文章的内容进行展示
    form.body.data = post.body
    form.category.data = post.category_id

    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
@confirm_required
def delete_post(post_id):
    """
        删除文章
    :param post_id:
    :return:
    """

    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()

blog/blueprints/blog.py
"""
    博客蓝图

    为蓝图增加蓝图的路由的两种方式：
        1. 使用装饰器，蓝图对象.route()  -->  先将路由注册到蓝图对象上，当将蓝图对象注册到程序实例上的时候，在将路由注册到程序实例上

            对于蓝图对象的理解：
                1。 蓝图对象是一种命名空间，使用蓝图对象添加的路由，都属于蓝图对象的命名空间上，可以通过app.url_map()来查看
                    Rule('/index'),  蓝图对象.endpoint  view_func()
                2.  使用蓝图对象可以实现项目结构的有序化的组织，可以将程序分离成不同的部分
        2. app.add_url_rule(rule, endpoint, view_func)
            在路由中，视图函数和url规则不是直接映射的，之所以不直接映射，是为了实现蓝图的命名空间
            如果存在多个同名的视图函数，会存在路由的冲突，增加了端点名作为媒介，可以实现不同命名空间的映射

    paginate()分页的使用：
        1。 接受的参数：page --> 页数  per-page --> 每页的个数， error_out ---> 当查询的页数超过总页数的行为
            max_per_page --> 设置每页查询的最大数量
            当error_out参数设置为True的时候，如果查询的页数超过最大值，或者是page或者per_page为负数或者非整型值的时候
            会返回404错误，如果设置为False，直接返回None，默认是True

        2. 对查询结果使用paginate方法传入相应的参数，可以返回一个分页对象，包含分页的信息
            分页对象一些常见的属性：
                has_next  --->    是否包含下一页，包含的时候返回True，不包含的时候返回False
                has_prev  --->    是否包含上一页，包含返回true，不包含返回false
                items     --->    返回分页之后的数据
                next_num  --->    下一页的页数，没有下一页返回None
                prev_num  --->    上一页的页数，没有上一页返回None
                page      --->    当前的页数
                pages     --->    总页数
                per_page  --->    每页的个数
                query     --->    分页的查询语句
                total     --->    总的记录的数量
            如果没有指定page参数和per_page参数，flask_sqlalchemy会自动从查询字符串中寻找对应的值
            如果没有获取到，，使用默认值，page=1，per_page=20
"""

from flask import Blueprint
from flask import request
from flask import current_app
from flask import render_template
from flask import abort
from flask import make_response
from flask import flash
from flask import redirect
from flask import url_for
from flask_login import current_user

from blog.models import Post, Category, Comment
from blog.utils import redirect_back
from blog.forms import AdminCommentForm, CommentForm
from blog.extensions import db

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    """首页视图"""
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)  # 生成一个分页对象
    posts = pagination.items   # 获取经过分页的数据

    return render_template('blog/index.html', pagination=pagination, posts=posts)


@blog_bp.route('/about')
def about():
    """展示关于的信息"""
    return render_template('blog/about.html')


@blog_bp.route('/category/<int:category_id>', methods=["GET"])
def show_category(category_id):
    """
        分类文章列表(边栏的分页文章)

        直接调用category.posts，会以列表的形式返回分类对应的文章，但是无法再次使用查询过滤器
        使用with_parent方法会返回查询的对象，可以链式调用查询过滤器
    :param category_id: 分类id
    :return:
    """
    category = Category.query.get_or_404(category_id)  # 获取当前的分类
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_POST_PER_PAGE']

    # 获取分页对象
    pagination = Post.query.with_parent(category).order_by(
        Post.timestamp.desc()).paginate(page, per_page=per_page)

    # 获取分页数据
    posts = pagination.items

    return render_template(
        'blog/category.html', pagination=pagination, category=category, posts=posts
    )


@blog_bp.route('/show_post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    """
        博客文章视图
    :param post_id: 文章id
    :return: 模板
    """

    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLUELOG_COMMENT_PER_PAGE']
    # 显示已经通过审核的评论
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(
        Comment.timestamp.asc()).paginate(page, per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        """如果当前的用户已经登陆，使用管理员的表单"""
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['BLUELOG_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True

    else:
        form = CommentForm()
        from_admin = False
        reviewed = False

    if form.validate_on_submit():
        """当表单认证通过的时候执行的操作"""
        author = form.author.data
        email = form.email.data
        site = form.email.data
        body = form.body.data
        comment = Comment(
            author=author, email=email, site=site, body=body,
            from_admin=from_admin, post=post, reviewed=reviewed
        )
        reply_id = request.args.get('reply')
        if reply_id:
            comment = Comment.query.get_or_404(reply_id)
            comment.replied_id = reply_id

        db.session.add(comment)
        db.session.commit()

        if current_user.is_authenticated:
            flash('评论成功')

        else:
            flash('你的评论已经提交，等待管理员的审核')
            # send_comment_email(post)  # 发送邮件
        return redirect(url_for('.show_post', post_id=post_id))

    return render_template(
        '/blog/post.html', post=post, pagination=pagination,
        comments=comments, form=form
    )


@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    """
        博客切换主体视图
        1.  将主题的名称存储在cookie中，名称为theme
    :param theme_name: 主体名
    :return:
    """
    # 判断配置项是否合法
    if theme_name not in current_app.config['BLUELOG_THEMES'].keys():
        abort(400)

    response = make_response(redirect_back())

    # set_cookie方法接受key ---> cookie名  value=""  --> cookie值, max_age=None, 过期时间  expires=None  --> 有效期,
    # 这里设置cookie的过期时间为30天
    response.set_cookie('theme', theme_name, max_age=30*24*60*60)

    return response


@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    """
        回复评论
    :param comment_id: 评论id
    :return:
    """

    comment = Comment.query.get_or_404(comment_id)
    if not comment.post.can_comment:
        """如果当前评论对应的文章不支持评论"""
        flash('当前文章不支持评论，请申请管理员开启评论')
        return redirect(url_for('.show_post', post_id=comment.post_id))

    return redirect(
        url_for('.show_post', post_id=comment.post_id, reply=comment_id, auth=comment.author)
    )

blog/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">{{ post.title }}</a></h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_post', post_id=post.id) }}">阅读更多</a></small>
        </p>
        <small>
            评论: <a href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            分类: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        <h5>No posts yet.</h5>
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('admin.new_post') }}">Write Now</a>
        {% endif %}
    </div>
{% endif %}

blog/templates/blog/_sidebar.html
{# 边栏局部模板 #}
{% if links %}
    <div class="card mb-3">
        <div class="card-header">热度</div>
        <ul class="list-group list-group-flush">
            {% for link in links %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if categories %}
    <div class="card mb-3">
        <div class="card-header">分类</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item  list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.show_category', category_id=category.id) }}">
                        {{ category.name }}
                    </a>
                    <span class="badge badge-primary badge-pill"> {{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}
<div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenuButton"
            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        更换主题
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for theme_name, display_name in config.BLUELOG_THEMES.items() %}
            <a class="dropdown-item"
               href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">
                {{ display_name }}</a>
        {% endfor %}
    </div>
</div>

blog/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>关于我</h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ admin.about|safe }}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>分类: {{ category.name }}</h1>
        <p class="text-muted">{{ category.posts|length }} 篇文章</p>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include "blog/_posts.html" %}
            <div class="page-footer">{{ render_pagination(pagination) }}</div>
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pager %}

{% block title %}主页{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
        <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pager(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ post.title }}
            <span class="float-right">
        {% if current_user.is_authenticated %}
            <a class="btn btn-info btn-sm" href="{{ url_for('admin_bp.edit_post', post_id=post.id) }}">编辑</a>
            <form class="inline" method="post"
                  action="{{ url_for('admin_bp.delete_post', post_id=post.id, next=url_for('blog.index')) }}">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('确定删除?');">删除
                </button>
            </form>
        {% endif %}
      </span>
        </h1>
        <small>
            分类: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a><br>
            日期: {{ moment(post.timestamp).format('LL') }}
        </small>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ post.body|safe }}
            <hr>
            <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">分享
            </button>
            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">永久链接</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments" id="comments">
                <h3>{{ pagination.total }} 条评论
                    <small>
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">
                            最新评论</a>
                    </small>
                    {# 当前用户已经登陆时的操作 #}
                    {% if current_user.is_authenticated %}
                        <form class="float-right" method="post"
                              action="{{ url_for('admin_bp.set_comment', post_id=post.id, next=request.full_path) }}">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                            <button type="submit" class="btn btn-warning btn-sm">
                                {% if post.can_comment %}关闭{% else %}开启{% endif %} 评论
                            </button>
                        </form>
                    {% endif %}
                </h3>
                {# 评论的展示 #}
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}"
                                           target="_blank">
                                            {% if comment.from_admin %}
                                                {{ admin.name }}
                                            {% else %}
                                                {{ comment.author }}
                                            {% endif %}
                                        </a>
                                        {% if comment.from_admin %}
                                            <span class="badge badge-primary">作者</span>{% endif %}
                                        {% if comment.replied %}<span class="badge badge-light">回复</span>{% endif %}
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                        {{ moment(comment.timestamp).fromNow() }}
                                    </small>
                                </div>
                                {% if comment.replied %}
                                    <p class="alert alert-dark reply-body">{{ comment.replied.author }}:
                                        <br>{{ comment.replied.body }}
                                    </p>
                                {%- endif -%}
                                <p class="mb-1">{{ comment.body }}</p>
                                <div class="float-right">
                                    <a class="btn btn-light btn-sm"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">回复</a>
                                    {% if current_user.is_authenticated %}
                                        <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">邮箱</a>
                                        <form class="inline" method="post"
                                              action="{{ url_for('admin_bp.delete_comment', comment_id=comment.id, next=request.full_path) }}">
                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return confirm('Are you sure?');">删除
                                            </button>
                                        </form>
                                    {% endif %}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="tip"><h5>暂无评论</h5></div>
                {% endif %}
            </div>
            {% if comments %}
                {{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
            {% if request.args.get('reply') %}
                <div class="alert alert-dark">
                    回复 ： <strong>{{ request.args.get('auth') }}</strong>:
                    <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">取消</a>
                </div>
            {% endif %}
            {% if post.can_comment %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
            {% else %}
                <div class="tip"><h5>禁止评论</h5></div>
            {% endif %}
        </div>
        <div class="col-sm-4 sidebar">
            {% include "blog/_sidebar.html" %}
        </div>
    </div>
{% endblock %}